version: "3"
services:
  consumer:
    image: consumer
    networks:
      - consumer-producer
    depends_on:
      - producer1
 
  producer1:
    image: producer1
    ports:
      - "8080:8080"
    networks:
      - consumer-producer 

networks:
  consumer-producer: